# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
##  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 127.0.0.1
  ip_ban_enabled: false
  login_attempts_threshold: 500

# MODBUS

modbus:
- name: VTR300
  close_comm_on_error: true
  delay: 1
  message_wait_milliseconds: 10
  retries: 5
  timeout: 1
  type: serial
  baudrate: 115200
  bytesize: 8
  method: rtu
  parity: N
  port: /dev/serial/by-id/usb-1a86_USB_Single_Serial_5434023441-if00
  stopbits: 1
  sensors: !include sensors.yaml