http:
  server_port: 80

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

panel_custom: !include panel_custom.yaml

# Text to speech
##  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# MODBUS

modbus:
- type: tcp
  host: 192.168.1.8
  port: 502
  name: "VTR300"
  #sensors: !include modbus_systemair.yml


# camera
#camera: 
#  - platform: generic
#    stream_source: !secret hik_addres_pass
#    authentication: basic

mqtt:

#vacuum:
#  - platform: viomi_vacuum_v8
#    host: 192.168.1.55
#    token: !secret xiaomi_token
#    name: 'Rydwan'

input_number:
  gas_meter_m3:
    name: Gas Meter Reading
    min: 0
    max: 999999
    step: 0.01
    unit_of_measurement: m³
    mode: box
    icon: 'mdi:fire'
  water_meter_m3:
    name: Water Meter Reading
    min: 0
    max: 999999
    step: 0.01
    unit_of_measurement: m³
    mode: box
    icon: 'mdi:water'

utility_meter:
  gas_house:
    source: input_number.gas_meter_m3
    name: gas_meter
    unique_id: gas_meter_uniqueid
  water_house:
    source: input_number.water_meter_m3
    name: water_meter
    unique_id: water_meter_uniqueid

# template:
#   - sensor:
#     - name: 'Gas Total'
#       device_class: gas
#       unit_of_measurement: m³
#       unique_id: gas_meter_uniqueid_template
#       state: "{{ state('input_number.gas_meter_m3') }}"
#       state_class: measurement
#     - name: 'Water Total'
#       device_class: water
#       unit_of_measurement: m³
#       unique_id: water_meter_uniqueid_template
#       state: "{{ state('input_number.water_meter_m3') }}"
#       state_class: measurement

sensor:
  - platform: template
    sensors:
      bateria:
        friendly_name: "Bateria akumulatorów"
        unique_id: battery_voltage
        unit_of_measurement: "V"
        value_template: "{{ '%0.1f'|format(states('sensor.a0_a1_voltage')|float * 11.89189) }}"

my: