substitutions:
  name: battery
  device_description: "Monitor battery"

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.batteryMonitor"
    version: 1.0.0

esp32:
  board: esp32dev
  framework:
    type: arduino
    version: 2.0.9

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret key_batteryMonitor

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # ...
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.233
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-5B1930"
    password: "Z1i8xrkpGInp"

captive_portal:
    
i2c:
  sda: GPIO21
  scl: GPIO22

ads1115:
  - address: 0x48

sensor:
  - platform: ads1115 #BATERIA
    multiplexer: 'A0_A1'
    gain: 4.096
    name: "A0_A1 Voltage"
    unit_of_measurement: "V"
    update_interval: 1s
    accuracy_decimals: 4
    filters:
      -  lambda: return x;