esphome:
  name: okap
  friendly_name: okap

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret key_okap

ota:
  password: !secret password_okap

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # ...
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.213
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Okap Fallback Hotspot"
    password: "mPVXQPFhMu4B"

captive_portal:
    
servo:
  - id: my_servo
    output: pwm_output
    min_level: 0.9
    max_level: 0.9
    idle_level: 0.075
    restore: False
    auto_detach_time: 0s
    transition_length: 0s

output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: D1
    frequency: 50Hz

switch:
  - platform: template
    name: "Serwomechanizm"
    icon: "mdi:screwdriver"
    turn_on_action:
      - servo.write:
          id: my_servo
          level: 0
    turn_off_action:
      - servo.write:
          id: my_servo
          level: 1.0